# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-30 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category_choices', models.CharField(choices=[('11', 'Vegetation'), ('12', 'Trees'), ('13', 'Nature'), ('14', 'Abstract'), ('15', 'Painting'), ('16', 'Animals'), ('17', 'Illustrations'), ('18', 'Flowers'), ('19', 'Business'), ('20', 'Industries'), ('21', 'Cats'), ('22', 'Car'), ('23', 'People'), ('24', 'Travel')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=20)),
                ('image_description', models.CharField(max_length=30)),
                ('image', models.ImageField(blank='True', null='True', upload_to='photos/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Category')),
            ],
            options={
                'ordering': ['image_name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Location'),
        ),
    ]
